### ISSUE TITLE
Undefined reference to glProgramParameteri and glGetProgramBinary

### ISSUE THREAD

**Issue by chenxiaolong** [soreau/dolphin-emu#1]
I'm currently having an issue with building the wayland-egl branch. It's failing to find `glProgramParameteri` and `glGetProgramBinary` for some reason.

Full build log: http://paste.kde.org/673604/raw/

Both the latest dolphin-git (from googlecode) and the master branch of your git repo build fine.

Any ideas? I'm really exited to test out dolphin-emu on Wayland :)

Thanks in advance!

**Comment by soreau** [comment]
What graphics drivers are you using? If you're using open drivers, make sure you have latest mesa.

**Comment by chenxiaolong** [comment]
Thanks for the reply!

I'm using mesa 9.0.2 with Intel HD3000 Sandy Bridge graphics.

**Comment by soreau** [comment]
The mesa version I am using here is 9.2-devel. You might be able to upgrade to latest mesa using xorg-edgers ppa. Make sure you have the mesa GL and EGL headers installed as well.

**Comment by chenxiaolong** [comment]
I finally fixed the issue, although I'm still not sure why it happens. I had to set `CXXFLAGS` to point to the correct include and library directories (my git mesa is in /opt/wayland) for the compilation to work:

```
CXXFLAGS="-I/opt/wayland/include -L/opt/wayland/lib" 
```

**Comment by soreau** [comment]
Ah yes, I had some trouble with this as well. It should be picked up by setting -DCMAKE_PREFIX_PATH. It is a good idea to install everything into the same prefix.

**Comment by chenxiaolong** [comment]
Ah, that's probably why. I have mesa, wayland, and weston installed in /opt/wayland and dolphin installed in /opt/dolphin-emu-wayland. I was compiling with this:

```
cmake .. \
  -DCMAKE_INSTALL_PREFIX=/opt/dolphin-emu-wayland \
  -DCMAKE_PREFIX_PATH=/opt/dolphin-emu-wayland    \
  -DUSE_EGL=1 -DDISABLE_WX=1     \
  -DUSE_X11=1 -DUSE_WAYLAND=1    \
  -DCMAKE_BUILD_TYPE=Debug       \
  -DCMAKE_VERBOSE_MAKEFILE=0
```

Anyway, I'm happy that it's working now :)
